### ISSUE TITLE
Setting for is_home graphic

### ISSUE THREAD

**Issue by kraftbj** [pmgllc/genesis-minimum-images-extended#6]
I'd like to add a setting on what the home graphic should be instead of using the sample.jpg. 

Long day here too, so for later.

**Comment by pmgllc** [comment]
I agree. I JUST now put it up on one of my live sites and none of the banners are there, so I'll tweak code tonight. I'd like to see where I went wrong. Is there a quicker way to deploy this code to my site than delete the local copy, download, and upload the new copy?

I know partly why it's gone, but I'd like to fix this:
![Screen Shot 2013-01-08 at 5 41 00 PM](https://f.cloud.github.com/assets/1641678/51920/86807b92-59e4-11e2-8919-925e38362e5c.png)

Other than that, the plugin is working without errors. ;-)

**Comment by kraftbj** [comment]
If you're building on localhost, you could git pull directly into the
folder of the plugin (since there isn't any activation code). Might be able
to do something similar if deploying vit git to wpengine's staging, but
haven't tried it before myself.

**Comment by pmgllc** [comment]
Just a quick update: I got the code changed how I thought it needed to be and I got the homepage banner back, but then when I went to single posts, the content skipped the banner image because I didn't have one selected yet and then the load stopped at the page-title.php section with nothing after that.

I went to the dashboard to add a banner image to the post and I was getting server 500 errors on the dashboard side only. Still looking for glaring reasons wny that happened, so I am guessing output.php is fine and admin.php is where I need to look. Right after I finish writing my post for midnight. 

(I'm not doing localhost on this, nor staging. I want it to be real-world, so I'm doing quick looks).
